services:
  anypod:
    image: ghcr.io/thurstonsand/anypod:nightly
    container_name: anypod
    restart: unless-stopped

    ports:
      - "8024:8024"
      - "8025:8025"

    volumes:
      # Configuration file
      - ./example_feeds.yaml:/config/feeds.yaml

      # Data directory for database and media files
      - ./test-data:/data

      # Optional: cookies.txt for authentication
      # - ./cookies.txt:/cookies/cookies.txt

      # System timezone
      - /etc/localtime:/etc/localtime:ro

    environment:
      # Identity / permissions
      PUID: 501
      PGID: 20

      SERVER_PORT: 8024 # Public server port
      ADMIN_SERVER_PORT: 8025 # Admin server port (keep private)

      # Optional: point to mounted cookies file for authenticated feeds
      # COOKIES_PATH: /cookies/cookies.txt

      # External URL (set when behind a reverse proxy)
      # BASE_URL: https://reverseproxy.example

      # Trusted proxy networks; enables X-Forwarded-* processing
      # TRUSTED_PROXIES:
      #   - "192.168.1.0/24"
      #   - "192.168.3.213" # e.g. your reverse proxy

      # Logging
      # LOG_FORMAT: json                     # json | human
      # LOG_LEVEL: INFO                      # DEBUG | INFO | WARNING | ERROR
      # LOG_INCLUDE_STACKTRACE: "false"      # true to include stack traces

      # Timezone for date parsing in config (optional)
      # TZ: "America/New_York"

      # yt-dlp update behavior
      # YT_CHANNEL: stable                   # stable | nightly | master | version
      # YT_DLP_UPDATE_FREQ: 12h              # e.g., 6h, 12h, 1d

      # Optional: YouTube PO Token provider for yt-dlp
      POT_PROVIDER_URL: http://bgutil-provider:4416

    depends_on:
      - bgutil-provider

  bgutil-provider:
    image: brainicism/bgutil-ytdlp-pot-provider:latest
    container_name: bgutil-provider
    restart: unless-stopped
    ports:
      - "4416:4416"
