name: "Bug report"
description: "Something didn't work"
title: "[bug] <summary>"
labels: ["type:bug"]
body:
  - type: textarea
    id: happened
    attributes:
      label: What happened?
      description: Short and specific. Redactions are fine.
      placeholder: "Describe the issue in 1-3 sentences."
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected
      placeholder: "What you thought would happen."

  - type: textarea
    id: steps
    attributes:
      label: Steps
      description: Exact steps help reproduce.
      placeholder: |
        1. Start container / run command
        2. Call endpoint or open feed
        3. Observe error

  - type: dropdown
    id: source
    attributes:
      label: Source type
      options: ["YouTube", "Patreon", "X/Twitter", "Other"]

  - type: input
    id: version
    attributes:
      label: Version or image tag
      placeholder: "ghcr.io/thurstonsand/anypod:latest | nightly | <commit>"

  - type: input
    id: env
    attributes:
      label: Environment
      placeholder: "Ubuntu 22.04 x86_64, Docker Compose"

  - type: textarea
    id: feed_yaml
    attributes:
      label: Minimal feed YAML
      description: Remove secrets. Keep it minimal.
      render: yaml
      placeholder: |
        feeds:
          myfeed:
            source: "https://www.youtube.com/playlist?list=..."

  - type: textarea
    id: logs
    attributes:
      label: Logs or screenshot
      description: Paste the relevant error lines or drag a screenshot.
      render: shell