name: "Feature request"
description: "Suggest an improvement"
title: "[feature] <summary>"
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        **AI copy-paste block**
        ```text
        TITLE:
        PROBLEM:
        PROPOSED SOLUTION:
        EXAMPLE (YAML or HTTP):
        SOURCE(S): [YouTube|Patreon|X/Twitter|All]
        EXTRA CONTEXT:
        ```

  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: What problem do you have?
      placeholder: "One paragraph max."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      placeholder: "Describe what Anypod should do."

  - type: textarea
    id: example
    attributes:
      label: Example (optional)
      description: A small config or endpoint sketch.
      render: yaml
      placeholder: |
        feeds:
          myfeed:
            option: value

  - type: dropdown
    id: sources
    attributes:
      label: Source(s) (optional)
      multiple: true
      options: ["YouTube", "Patreon", "X/Twitter", "All", "Other"]

  - type: textarea
    id: context
    attributes:
      label: Extra context (optional)
      placeholder: "Links, prior art, screenshots."
