name: "Feature request"
description: "Suggest an improvement"
title: "[feature] <summary>"
labels: ["type:enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: What problem do you have?
      placeholder: "One paragraph max."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      placeholder: "Describe what Anypod should do."

  - type: textarea
    id: example
    attributes:
      label: Example
      description: A small config or endpoint sketch.
      render: yaml
      placeholder: |
        feeds:
          myfeed:
            option: value

  - type: dropdown
    id: sources
    attributes:
      label: Source(s)
      multiple: true
      options: ["YouTube", "Patreon", "X/Twitter", "All", "Other"]

  - type: textarea
    id: context
    attributes:
      label: Extra context
      placeholder: "Links, prior art, screenshots."
