# type: ignore
# ruff: noqa
# fmt: off

"""Add resolved_url field to feed table

Revision ID: 56d11f3bc82c
Revises: 78f7e4e33398
Create Date: 2025-06-27 04:44:48.536283

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlmodel.sql.sqltypes import AutoString


# revision identifiers, used by Alembic.
revision: str = '56d11f3bc82c'
down_revision: Union[str, Sequence[str], None] = '78f7e4e33398'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feed', sa.Column('resolved_url', AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('feed', 'resolved_url')
    # ### end Alembic commands ###
