# type: ignore
# ruff: noqa
# fmt: off

"""Add podcast_type and author_email fields to feed table

Revision ID: 23cf24f50086
Revises: 56d11f3bc82c
Create Date: 2025-07-10 22:34:11.777029

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlmodel.sql.sqltypes import AutoString


# revision identifiers, used by Alembic.
revision: str = '23cf24f50086'
down_revision: Union[str, Sequence[str], None] = '56d11f3bc82c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feed', sa.Column('author_email', AutoString(), nullable=True))
    op.add_column('feed', sa.Column('podcast_type', sa.Enum('EPISODIC', 'SERIAL', name='podcasttype'), server_default='EPISODIC', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('feed', 'podcast_type')
    op.drop_column('feed', 'author_email')
    # ### end Alembic commands ###
