#!/usr/bin/env python3
"""Script to sync CLAUDE.md files into AGENTS.md for OpenAI Codex compatibility."""

from pathlib import Path
import sys


def main() -> int:
    """Merge CLAUDE.md files into AGENTS.md."""
    repo_root = Path(__file__).parent.parent

    # Read source files
    root_claude = repo_root / "CLAUDE.md"
    tests_claude = repo_root / "tests" / "CLAUDE.md"
    agents_md = repo_root / "AGENTS.md"

    if not root_claude.exists():
        print(f"Error: {root_claude} not found", file=sys.stderr)
        return 1

    if not tests_claude.exists():
        print(f"Error: {tests_claude} not found", file=sys.stderr)
        return 1

    # Read contents
    root_content = root_claude.read_text(encoding="utf-8")
    tests_content = tests_claude.read_text(encoding="utf-8")

    # Create merged content
    merged_content = f"""# AGENTS.md

⚠️ **This file is auto-generated from CLAUDE.md files. Do not edit directly.**

This file is automatically generated by merging the project's CLAUDE.md files for OpenAI Codex compatibility. The source of truth is the individual CLAUDE.md files.

---

# Project Instructions (Global)

The following instructions apply to all files in the project:

{root_content}

---

# Testing-Specific Instructions

**The following instructions apply ONLY when editing or creating files under the `tests/` directory:**

{tests_content}
"""

    # Write merged content
    agents_md.write_text(merged_content, encoding="utf-8")
    print(f"Successfully synced CLAUDE.md files to {agents_md}")

    return 0


if __name__ == "__main__":
    sys.exit(main())
