name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read # Default permission for checkout

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: latest
          enable-cache: true
          cache-dependency-glob: "uv.lock"
      - name: Install project dependencies
        run: uv sync --locked --all-extras --dev
      - name: Run pre-commit
        uses: pre-commit/action@v3.0.1

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v5
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: latest
          enable-cache: true
          cache-dependency-glob: "uv.lock"
      - name: Install project dependencies
        run: uv sync --locked --all-extras --dev
      - name: Run tests with coverage
        run: |
          uv run pytest --cov-report xml

      # - name: Upload coverage to Codecov
      #   uses: codecov/codecov-action@v4
      #   with:
      #     token: ${{ secrets.CODECOV_TOKEN }}
      #     files: ./coverage.xml # coverage file
      #     fail_ci_if_error: true