name: "Update bgutil POT provider and Commit to Main"

permissions:
  contents: write

on:
  workflow_dispatch: # Allow manual triggering
  schedule:
    - cron: "0 1 * * *" # Runs daily at 01:00 UTC

jobs:
  update-and-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          ssh-key: ${{ secrets.ANYPOD_DEPLOY_KEY }}

      - name: Update bgutil POT provider and detect changes
        id: provider
        run: |
          set -euo pipefail
          LATEST=$(curl -s https://api.github.com/repos/brainicism/bgutil-ytdlp-pot-provider/releases/latest | jq -r '.tag_name')
          CURRENT=$(awk -F= '/^ARG BGUTIL_POT_PROVIDER_VERSION=/{print $2}' Dockerfile)
          if [ "$LATEST" = "$CURRENT" ]; then
            echo "update_needed=0" >> "$GITHUB_OUTPUT"
            echo "No changes to Dockerfile"
          else
            sed -i "s/^ARG BGUTIL_POT_PROVIDER_VERSION=.*/ARG BGUTIL_POT_PROVIDER_VERSION=${LATEST}/" Dockerfile
            echo "update_needed=1" >> "$GITHUB_OUTPUT"
            echo "bgutil_version=${LATEST}" >> "$GITHUB_OUTPUT"
            echo "Dockerfile updated to bgutil POT provider ${LATEST}"
          fi

      - name: Install uv
        if: steps.provider.outputs.update_needed == '1'
        uses: astral-sh/setup-uv@v6
        with:
          version: latest
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Run pre-commit checks
        if: steps.provider.outputs.update_needed == '1'
        uses: pre-commit/action@v3.0.1

      - name: Run tests
        if: steps.provider.outputs.update_needed == '1'
        run: |
          uv run pytest --cov-report xml

      - name: Commit and push
        if: steps.provider.outputs.update_needed == '1'
        env:
          PROVIDER_VERSION: ${{ steps.provider.outputs.bgutil_version }}
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add Dockerfile
          echo "Committing Dockerfile update for bgutil POT provider ${PROVIDER_VERSION} (tests passed)"
          git commit -m "chore(deps): update bgutil POT provider to ${PROVIDER_VERSION}

          Auto-update performed by GitHub Actions after validating:
            - Dockerfile version update successful
            - Pre-commit checks passed
            - All tests passed"
          git push origin main
